main: de.rangun.tabworlddate.TABWorldDatePlugin
name: TABWorldDate
version: '@version@'
description: TAB addon plugin providing a placeholder for the world's current Gregorian date
authors:
  - Velnias75
website: https://github.com/velnias75/TABWorldDate
api-version: '1.16'
depend: [TAB]
